# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\harry\Desktop\Lab\Project_spikesorter\PySortGUI\UI\SelectEventsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectEventsDialog(object):
    def setupUi(self, SelectEventsDialog):
        SelectEventsDialog.setObjectName("SelectEventsDialog")
        SelectEventsDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectEventsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SelectEventsDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.select_all_checkBox = QtWidgets.QCheckBox(SelectEventsDialog)
        self.select_all_checkBox.setObjectName("select_all_checkBox")
        self.verticalLayout.addWidget(self.select_all_checkBox)
        self.tableView = QtWidgets.QTableView(SelectEventsDialog)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectEventsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SelectEventsDialog)
        self.buttonBox.accepted.connect(SelectEventsDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SelectEventsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectEventsDialog)

    def retranslateUi(self, SelectEventsDialog):
        _translate = QtCore.QCoreApplication.translate
        SelectEventsDialog.setWindowTitle(_translate("SelectEventsDialog", "Dialog"))
        self.label.setText(_translate("SelectEventsDialog", "Select events:"))
        self.select_all_checkBox.setText(_translate("SelectEventsDialog", "select all"))
