# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\harry\Desktop\Lab\Project_spikesorter\try\UI\TimelineView.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimelineView(object):
    def setupUi(self, TimelineView):
        TimelineView.setObjectName("TimelineView")
        TimelineView.resize(305, 112)
        font = QtGui.QFont()
        font.setPointSize(12)
        TimelineView.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TimelineView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotLayout = QtWidgets.QVBoxLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout.addLayout(self.plotLayout)
        self.groupBox = QtWidgets.QGroupBox(TimelineView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.events_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.events_pushButton.setCheckable(True)
        self.events_pushButton.setObjectName("events_pushButton")
        self.verticalLayout_2.addWidget(self.events_pushButton)
        self.thr_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.thr_pushButton.setCheckable(True)
        self.thr_pushButton.setObjectName("thr_pushButton")
        self.verticalLayout_2.addWidget(self.thr_pushButton)
        self.spikes_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.spikes_pushButton.setCheckable(True)
        self.spikes_pushButton.setObjectName("spikes_pushButton")
        self.verticalLayout_2.addWidget(self.spikes_pushButton)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.raw_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.raw_pushButton.setCheckable(True)
        self.raw_pushButton.setAutoDefault(False)
        self.raw_pushButton.setDefault(False)
        self.raw_pushButton.setObjectName("raw_pushButton")
        self.verticalLayout_2.addWidget(self.raw_pushButton)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(TimelineView)
        QtCore.QMetaObject.connectSlotsByName(TimelineView)

    def retranslateUi(self, TimelineView):
        _translate = QtCore.QCoreApplication.translate
        TimelineView.setWindowTitle(_translate("TimelineView", "Form"))
        self.events_pushButton.setText(_translate("TimelineView", "events"))
        self.thr_pushButton.setText(_translate("TimelineView", "threshold"))
        self.spikes_pushButton.setText(_translate("TimelineView", "spikes"))
        self.raw_pushButton.setText(_translate("TimelineView", "raw"))
