# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\harry\Desktop\Lab\Project_spikesorter\try\UI\ChannelDetailv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChannelDetail(object):
    def setupUi(self, ChannelDetail):
        ChannelDetail.setObjectName("ChannelDetail")
        ChannelDetail.resize(186, 212)
        font = QtGui.QFont()
        font.setPointSize(12)
        ChannelDetail.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChannelDetail)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_name_lineEdit = QtWidgets.QLineEdit(ChannelDetail)
        self.file_name_lineEdit.setEnabled(False)
        self.file_name_lineEdit.setText("")
        self.file_name_lineEdit.setObjectName("file_name_lineEdit")
        self.horizontalLayout.addWidget(self.file_name_lineEdit)
        self.open_file_toolButton = QtWidgets.QToolButton(ChannelDetail)
        self.open_file_toolButton.setObjectName("open_file_toolButton")
        self.horizontalLayout.addWidget(self.open_file_toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeView = QtWidgets.QTreeView(ChannelDetail)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sorting_type_label = QtWidgets.QLabel(ChannelDetail)
        self.sorting_type_label.setObjectName("sorting_type_label")
        self.horizontalLayout_2.addWidget(self.sorting_type_label)
        self.sorting_label_comboBox = QtWidgets.QComboBox(ChannelDetail)
        self.sorting_label_comboBox.setEditable(True)
        self.sorting_label_comboBox.setObjectName("sorting_label_comboBox")
        self.horizontalLayout_2.addWidget(self.sorting_label_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.extract_wav_pushButton = QtWidgets.QPushButton(ChannelDetail)
        self.extract_wav_pushButton.setObjectName("extract_wav_pushButton")
        self.horizontalLayout_6.addWidget(self.extract_wav_pushButton)
        self.extract_wav_setting_toolButton = QtWidgets.QToolButton(ChannelDetail)
        self.extract_wav_setting_toolButton.setObjectName("extract_wav_setting_toolButton")
        self.horizontalLayout_6.addWidget(self.extract_wav_setting_toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sort_channel_pushButton = QtWidgets.QPushButton(ChannelDetail)
        self.sort_channel_pushButton.setObjectName("sort_channel_pushButton")
        self.horizontalLayout_5.addWidget(self.sort_channel_pushButton)
        self.sort_methods_toolButton = QtWidgets.QToolButton(ChannelDetail)
        self.sort_methods_toolButton.setObjectName("sort_methods_toolButton")
        self.horizontalLayout_5.addWidget(self.sort_methods_toolButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(ChannelDetail)
        QtCore.QMetaObject.connectSlotsByName(ChannelDetail)

    def retranslateUi(self, ChannelDetail):
        _translate = QtCore.QCoreApplication.translate
        ChannelDetail.setWindowTitle(_translate("ChannelDetail", "Form"))
        self.open_file_toolButton.setText(_translate("ChannelDetail", "..."))
        self.sorting_type_label.setText(_translate("ChannelDetail", "Sorting label"))
        self.extract_wav_pushButton.setText(_translate("ChannelDetail", "Extract Waveform"))
        self.extract_wav_setting_toolButton.setText(_translate("ChannelDetail", "..."))
        self.sort_channel_pushButton.setText(_translate("ChannelDetail", "Sort channal"))
        self.sort_methods_toolButton.setText(_translate("ChannelDetail", "..."))
