# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\harry\Desktop\Lab\Project_spikesorter\PySortGUI\UI\CreateReferenceDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateReferenceDialog(object):
    def setupUi(self, CreateReferenceDialog):
        CreateReferenceDialog.setObjectName("CreateReferenceDialog")
        CreateReferenceDialog.resize(400, 300)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(CreateReferenceDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CreateReferenceDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(CreateReferenceDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.channel_name_lineEdit = QtWidgets.QLineEdit(CreateReferenceDialog)
        self.channel_name_lineEdit.setObjectName("channel_name_lineEdit")
        self.verticalLayout_2.addWidget(self.channel_name_lineEdit)
        self.comment_lineEdit = QtWidgets.QLineEdit(CreateReferenceDialog)
        self.comment_lineEdit.setObjectName("comment_lineEdit")
        self.verticalLayout_2.addWidget(self.comment_lineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(CreateReferenceDialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.tableView = QtWidgets.QTableView(CreateReferenceDialog)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateReferenceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(CreateReferenceDialog)
        self.buttonBox.accepted.connect(CreateReferenceDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateReferenceDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateReferenceDialog)

    def retranslateUi(self, CreateReferenceDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateReferenceDialog.setWindowTitle(_translate("CreateReferenceDialog", "Dialog"))
        self.label.setText(_translate("CreateReferenceDialog", "Channel Name"))
        self.label_2.setText(_translate("CreateReferenceDialog", "Comment(Optional)"))
        self.label_3.setText(_translate("CreateReferenceDialog", "Select Channels:"))
