# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\harry\Desktop\Lab\Project_spikesorter\try\UI\TimelineViewUIv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(305, 112)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openGLWidget = QtWidgets.QOpenGLWidget(Form)
        self.openGLWidget.setObjectName("openGLWidget")
        self.verticalLayout.addWidget(self.openGLWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_events = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_events.setCheckable(True)
        self.pushButton_events.setObjectName("pushButton_events")
        self.verticalLayout_2.addWidget(self.pushButton_events)
        self.pushButton_thr = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_thr.setCheckable(True)
        self.pushButton_thr.setObjectName("pushButton_thr")
        self.verticalLayout_2.addWidget(self.pushButton_thr)
        self.pushButton_spikes = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_spikes.setCheckable(True)
        self.pushButton_spikes.setObjectName("pushButton_spikes")
        self.verticalLayout_2.addWidget(self.pushButton_spikes)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_events.setText(_translate("Form", "events"))
        self.pushButton_thr.setText(_translate("Form", "threshold"))
        self.pushButton_spikes.setText(_translate("Form", "spikes"))
